set -g mouse on
set -g history-limit 100000
setw -g mode-keys vi
set -g base-index 1
setw -g pane-base-index 1

set -g status on
set -g status-interval 1
set -g status-justify left
set -g status-bg "#262626"
set -g status-fg "#e0def4"
set -g status-style default

set -g window-status-format "#[fg=#9ccfd8] #I:#W- "
set -g window-status-current-format "#[fg=#9ccfd8] #I:#W#F "

set -g status-left-length 60
set -g status-left " #[fg=#9ccfd8][#[fg=#9ccfd8]#S] "

set -g status-right-length 60
set -g status-right "#[fg=#9ccfd8][#[fg=#9ccfd8]#H] #[fg=#9ccfd8]%Y-%m-%d "

set -g pane-border-style fg="#6e6a86"
set -g pane-active-border-style fg="#9ccfd8"

bind -T copy-mode-vi v send -X begin-selection
bind -T copy-mode-vi y send -X copy-selection-and-cancel
bind-key -T copy-mode-vi MouseDragEnd1Pane send -X copy-selection-and-cancel

bind r source-file ~/.tmux.conf \; display-message "config reloaded"

set-option -g allow-rename off
set-option -g automatic-rename off
